providers = ["node"]

[variables]
PUPPETEER_SKIP_DOWNLOAD = "true"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
