[build]
builder = "nixpacks"
installCommand = "export PUPPETEER_SKIP_DOWNLOAD=true NPM_CONFIG_PRODUCTION=false && npm install --include=dev"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
