[providers]
providers = ["node"]

[variables]
PUPPETEER_SKIP_DOWNLOAD = "true"
HOST = "0.0.0.0"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install --prefix web"]

[phases.build]
cmds = ["npm run build --prefix web"]

[start]
cmd = "npm run start --prefix web"
