[build]
builder = "nixpacks"
installCommand = "cd ovrload-web && npm install"
buildCommand = "cd ovrload-web && npm run build"

[deploy]
startCommand = "cd ovrload-web && npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
