import sql from "@/app/api/utils/sql";
import { getAdminWithRolesFromRequest } from "@/app/api/utils/adminAuth";
import {
  toLebanonE164,
  normalizePhone as normalizePhoneUtil,
  sendWhatsAppPayload,
} from "@/app/api/utils/customerWhatsApp";
import {
  getTemplateConfig,
  buildPayloadFromSchema,
} from "@/app/api/utils/whatsappTemplateRegistry";

// The only provisioned sender in Infobip for this account
const FORCED_SENDER = "96176489078";

const normalizePhone = (phone) => normalizePhoneUtil(phone);

const formatMoney = (value) => {
  const num = Number.parseFloat(value);
  const safe = Number.isFinite(num) ? num : 0;
  return `$${safe.toFixed(2)}`;
};

const formatBeirutDateTime = (dateLike) => {
  const date = dateLike ? new Date(dateLike) : new Date();
  const time = new Intl.DateTimeFormat("en-US", {
    timeZone: "Asia/Beirut",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).format(date);
  const datePart = new Intl.DateTimeFormat("en-US", {
    timeZone: "Asia/Beirut",
    month: "short",
    day: "2-digit",
    year: "numeric",
  }).format(date);
  return `${time} – ${datePart}`;
};

const buildAddressText = (address) => {
  if (!address) return "N/A";
  const parts = [];
  if (address.address_line1) parts.push(String(address.address_line1).trim());
  if (address.address_line2) parts.push(String(address.address_line2).trim());
  if (address.building) parts.push(String(address.building).trim());
  const cityLine = [address.city, address.state, address.zip_code]
    .filter(Boolean)
    .map((s) => String(s).trim())
    .join(", ");
  if (cityLine) parts.push(cityLine);
  return parts.join(" — ").trim() || "N/A";
};

const buildMapsLink = ({ latitude, longitude } = {}) => {
  const lat = Number.parseFloat(latitude);
  const lng = Number.parseFloat(longitude);
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) return null;
  return `https://www.google.com/maps?q=${lat},${lng}`;
};

async function ensureWhatsAppLogsTable() {
  await sql`
    CREATE TABLE IF NOT EXISTS public.whatsapp_logs (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id integer NOT NULL,
      branch_id integer,
      to_phone text NOT NULL,
      message_text text NOT NULL,
      status text NOT NULL,
      provider_message_id text,
      error text,
      created_at timestamp with time zone NOT NULL DEFAULT now()
    )
  `;
}

async function getRateLimitState(orderId) {
  await ensureWhatsAppLogsTable();
  const [{ count_10m }] = await sql`
    SELECT COUNT(*)::int AS count_10m
    FROM whatsapp_logs
    WHERE order_id = ${Number(orderId)}
      AND created_at > now() - interval '10 minutes'
  `;
  const [lastSent] = await sql`
    SELECT created_at FROM whatsapp_logs
    WHERE order_id = ${Number(orderId)} AND status = 'sent'
    ORDER BY created_at DESC LIMIT 1
  `;
  const count10m = Number.parseInt(count_10m ?? 0, 10) || 0;
  const lastSentAt = lastSent?.created_at
    ? new Date(lastSent.created_at)
    : null;
  const sentRecently = lastSentAt
    ? lastSentAt.getTime() > Date.now() - 2 * 60 * 1000
    : false;
  return { count10m, sentRecently, lastSentAt };
}

export async function POST(request) {
  console.log("[send-whatsapp] POST hit — template mode (delivery_to_branch)");

  let orderId = null;
  let branchId = null;
  let toPhone = null;
  let messageText = "";

  try {
    // ── Auth ───────────────────────────────────────────────────────────────
    const admin = await getAdminWithRolesFromRequest(request);
    if (!admin) {
      return Response.json(
        { ok: false, error: "Admin authentication required" },
        { status: 401 },
      );
    }

    const roles = Array.isArray(admin?.roles) ? admin.roles : [];
    if (!roles.includes("orders") && !roles.includes("backend")) {
      return Response.json(
        { ok: false, error: "Unauthorized - orders permission required" },
        { status: 403 },
      );
    }

    // ── Parse body ─────────────────────────────────────────────────────────
    const body = (await request.json().catch(() => ({}))) || {};
    orderId = body?.orderId;
    const dryRun = body?.dryRun === true;
    const force = body?.force === true;

    if (!orderId) {
      return Response.json(
        { ok: false, error: "orderId is required" },
        { status: 400 },
      );
    }

    // ── Load order ─────────────────────────────────────────────────────────
    const [order] = await sql`
      SELECT id, user_id, branch_id, address_id, created_at,
             subtotal_amount, delivery_fee, total_amount,
             total_after_discount, special_instructions
      FROM orders WHERE id = ${Number(orderId)} LIMIT 1
    `;
    if (!order) {
      return Response.json(
        { ok: false, error: "Order not found" },
        { status: 404 },
      );
    }

    branchId = order.branch_id || null;

    const [branch] = order.branch_id
      ? await sql`SELECT id, name, whatsapp_phone, phone FROM branches WHERE id = ${Number(order.branch_id)} LIMIT 1`
      : [null];

    const [user] = order.user_id
      ? await sql`SELECT id, name, first_name, last_name, phone FROM auth_users WHERE id = ${Number(order.user_id)} LIMIT 1`
      : [null];

    const [address] = order.address_id
      ? await sql`
          SELECT id, address_line1, address_line2, city, state,
                 zip_code, latitude, longitude, building
          FROM user_addresses WHERE id = ${Number(order.address_id)} LIMIT 1
        `
      : [null];

    // ── Validate branch phone ──────────────────────────────────────────────
    if (!branch) {
      return Response.json(
        {
          ok: false,
          error: "Order is missing branch information",
          canSend: false,
        },
        { status: 400 },
      );
    }

    const storePhoneRaw = branch?.whatsapp_phone
      ? String(branch.whatsapp_phone)
      : branch?.phone
        ? String(branch.phone)
        : "";

    if (!storePhoneRaw) {
      return Response.json(
        {
          ok: false,
          error:
            "No store WhatsApp number set. Please set branches.whatsapp_phone (preferred) or branches.phone.",
          canSend: false,
        },
        { status: 400 },
      );
    }

    toPhone = toLebanonE164(storePhoneRaw);

    // ── Load template (delivery_to_branch) — same pattern as new_order_to_branch ──
    const templateConfig = await getTemplateConfig("delivery_to_branch");
    if (!templateConfig) {
      return Response.json(
        {
          ok: false,
          error:
            "WhatsApp template 'delivery_to_branch' is not configured. " +
            "Go to Admin → Settings → WhatsApp Templates and configure it with key: delivery_to_branch",
          canSend: false,
        },
        { status: 400 },
      );
    }

    const { templateName, language, schema } = templateConfig;

    // ── Build preview text (human-readable, for UI) ────────────────────────
    const clientName =
      user?.name ||
      [user?.first_name, user?.last_name].filter(Boolean).join(" ") ||
      "Guest";
    const clientPhoneRaw = user?.phone ? String(user.phone) : "";
    const clientPhone = clientPhoneRaw ? normalizePhone(clientPhoneRaw) : "N/A";
    const addressText = buildAddressText(address);
    const mapsLink = buildMapsLink(address || {});
    const orderAmountRaw =
      order.total_after_discount != null
        ? order.total_after_discount
        : order.total_amount;
    const deliveryFeeRaw = order.delivery_fee != null ? order.delivery_fee : 0;

    messageText = [
      `🛵 New Delivery Order #${order.id}`,
      `👤 Client: ${clientName}`,
      `📞 Phone: ${clientPhone}`,
      `📍 Address: ${addressText}`,
      mapsLink ? `🗺 Location: ${mapsLink}` : null,
      `💰 Order: ${formatMoney(orderAmountRaw)} | 🚚 Delivery: ${formatMoney(deliveryFeeRaw)}`,
      `🕐 Placed: ${formatBeirutDateTime(order.created_at)}`,
      order.special_instructions
        ? `📝 Notes: ${String(order.special_instructions).trim()}`
        : null,
    ]
      .filter(Boolean)
      .join("\n");

    // ── Rate limit ─────────────────────────────────────────────────────────
    const { count10m, sentRecently } = await getRateLimitState(order.id);
    if (count10m >= 3) {
      return Response.json(
        {
          ok: false,
          error: "Rate limit: max 3 WhatsApp sends per order per 10 minutes",
          preview: messageText,
        },
        { status: 429 },
      );
    }

    // ── Dry run ────────────────────────────────────────────────────────────
    if (dryRun) {
      return Response.json({
        ok: true,
        preview: messageText,
        canSend: true,
        sentRecently,
        toPhone,
        phoneSource: branch?.whatsapp_phone ? "whatsapp_phone" : "phone",
        templateName,
        sender: FORCED_SENDER,
      });
    }

    // ── Duplicate guard ────────────────────────────────────────────────────
    if (sentRecently && !force) {
      return Response.json(
        {
          ok: false,
          error:
            "WhatsApp was already sent successfully in the last 2 minutes. Send again?",
          requireConfirm: true,
          preview: messageText,
          sender: FORCED_SENDER,
        },
        { status: 409 },
      );
    }

    // ── Build payload (same pattern as new_order_to_branch) ───────────────
    // Build placeholders dynamically based on what the template expects
    let placeholders = [];
    if (schema.bodyPlaceholderCount === 7) {
      placeholders = [
        String(order.id),
        clientName,
        clientPhone,
        addressText + (mapsLink ? `\n🗺 Location: ${mapsLink}` : ""),
        formatMoney(orderAmountRaw),
        formatMoney(deliveryFeeRaw),
        formatBeirutDateTime(order.created_at) + (order.special_instructions ? `\n📝 Notes: ${String(order.special_instructions).trim()}` : "")
      ];
    } else if (schema.bodyPlaceholderCount === 1) {
      // Fallback: send the entire message text as a single placeholder
      placeholders = [messageText];
    } else if (schema.bodyPlaceholderCount > 0) {
      placeholders = [String(order.id)]; // Default legacy behavior
    }

    console.log(
      `[send-whatsapp] Building payload for template: ${templateName}`,
    );
    console.log(
      `[send-whatsapp] from=${FORCED_SENDER} to=${toPhone} placeholders=${JSON.stringify(placeholders)}`,
    );

    const payload = buildPayloadFromSchema(
      schema,
      { templateName, language },
      { placeholders },
      FORCED_SENDER,
      toPhone,
    );

    // ── Send ───────────────────────────────────────────────────────────────
    let providerMessageId = null;

    try {
      const response = await sendWhatsAppPayload(payload);
      providerMessageId = response?.id || null;

      console.log(`[send-whatsapp] ✅ Sent. MessageId: ${providerMessageId}`);

      await sql`
        INSERT INTO whatsapp_logs
          (order_id, branch_id, to_phone, message_text, status, provider_message_id)
        VALUES
          (${Number(order.id)}, ${branchId ? Number(branchId) : null},
           ${toPhone}, ${messageText}, 'sent', ${providerMessageId})
      `;

      return Response.json({
        ok: true,
        sender: FORCED_SENDER,
        actualSenderSent: FORCED_SENDER,
        templateName,
        messageId: providerMessageId,
      });
    } catch (sendErr) {
      const errorMsg = String(sendErr?.message || sendErr || "Failed to send");
      console.error(`[send-whatsapp] ❌ Send failed:`, sendErr);

      await sql`
        INSERT INTO whatsapp_logs
          (order_id, branch_id, to_phone, message_text, status, error)
        VALUES
          (${Number(order.id)}, ${branchId ? Number(branchId) : null},
           ${toPhone || ""}, ${messageText}, 'failed', ${errorMsg})
      `.catch(() => {});

      return Response.json(
        {
          ok: false,
          error: errorMsg,
          sender: FORCED_SENDER,
          actualSenderSent: FORCED_SENDER,
        },
        { status: 500 },
      );
    }
  } catch (error) {
    console.error("[send-whatsapp] Outer error:", error);
    const msg = String(error?.message || "Failed to send WhatsApp");

    try {
      if (orderId) {
        await ensureWhatsAppLogsTable();
        await sql`
          INSERT INTO whatsapp_logs
            (order_id, branch_id, to_phone, message_text, status, error)
          VALUES
            (${Number(orderId)}, ${branchId ? Number(branchId) : null},
             ${toPhone || ""}, ${messageText}, 'failed', ${msg})
        `;
      }
    } catch (e) {
      console.error("[send-whatsapp] failed to log:", e);
    }

    return Response.json(
      { ok: false, error: msg, sender: FORCED_SENDER },
      { status: 500 },
    );
  }
}
